import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions | Nritya Bharathanjali 2026 – Skanda',
  description: 'Official Terms & Conditions for booking tickets to MS Naatyakshetra’s Nritya Bharathanjali 2026 – Skanda production.',
};

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8 relative overflow-hidden" style={{ background: 'var(--ivory)' }}>
      {/* Background Rotating Rangoli Mandala */}
      <img
        src="/assets/rangoli.png"
        alt=""
        aria-hidden="true"
        className="rangoli-bg spin-slow absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] opacity-10 pointer-events-none"
      />

      <div className="max-w-4xl mx-auto relative z-10">
        {/* Navigation Breadcrumb */}
        <div className="mb-6">
          <Link
            href="/"
            className="inline-flex items-center text-xs uppercase tracking-widest font-semibold transition-colors duration-200"
            style={{ color: 'var(--maroon)' }}
          >
            ← Back to Event Home
          </Link>
        </div>

        {/* Page Header */}
        <div className="text-center mb-10 pb-6 border-b" style={{ borderColor: 'var(--gold)' }}>
          <span
            className="text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full inline-block mb-3"
            style={{ background: 'var(--sandal)', color: 'var(--maroon)' }}
          >
            Legal Information
          </span>
          <h1 className="text-3xl sm:text-4xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
            Terms &amp; Conditions
          </h1>
          <p className="text-sm font-body max-w-xl mx-auto" style={{ color: 'var(--ink-soft)' }}>
            Nritya Bharathanjali 2026 – Skanda | MS Naatyakshetra Official E-Ticketing Platform
          </p>
        </div>

        {/* Policy Content Card */}
        <div
          className="p-6 sm:p-10 rounded-xl shadow-lg border leading-relaxed text-sm font-body space-y-8"
          style={{ background: 'var(--parchment)', borderColor: 'rgba(182, 138, 62, 0.3)', color: 'var(--ink)' }}
        >
          {/* Section 1 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              1. Electronic Record Notice
            </h2>
            <p>
              This document is an electronic record generated by a computer system in accordance with the Information Technology Act, 2000 and rules framed thereunder, as applicable, pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record does not require any physical or digital signatures.
            </p>
            <p className="mt-2">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name{' '}
              <a
                href="https://nritya-bharathanjali-ticketing.vercel.app/"
                target="_blank"
                rel="noreferrer"
                className="underline font-semibold"
                style={{ color: 'var(--maroon)' }}
              >
                https://nritya-bharathanjali-ticketing.vercel.app/
              </a>{' '}
              (hereinafter referred to as the &quot;Platform&quot; or &quot;Website&quot;).
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              2. Platform Ownership &amp; Scope of Services
            </h2>
            <p>
              The Platform is owned and operated by <strong>MS Naatyakshetra</strong> (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), with its principal office located at:
            </p>
            <p className="mt-2 font-semibold">
              1, Jayaramreddy layout, 2nd Main, 3rd Cross A-Block, AECS Layout, Kundalahalli, Brookefield, Bengaluru, Karnataka 560037
            </p>
            <p className="mt-2">
              The Platform is established exclusively for online ticket booking and digital admission pass reservation for the live classical dance production <strong>Nritya Bharathanjali 2026 – Skanda</strong> scheduled for <strong>September 26, 2026</strong>. The Platform does not sell physical consumer goods, merchandise, or third-party products.
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              3. Acceptance of Terms &amp; User Obligations
            </h2>
            <p>
              By accessing, browsing, or using the Platform, or by booking a ticket on the Platform, you (&quot;User&quot;, &quot;Buyer&quot;, or &quot;You&quot;) agree to be bound by these Terms &amp; Conditions, along with our Privacy Policy, Refund &amp; Cancellation Policy, Return Policy, and Shipping / Digital Delivery Policy.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>You agree to provide true, accurate, and complete contact information (including name, email address, and mobile number) during booking.</li>
              <li>You are responsible for maintaining the confidentiality of your booking acknowledgement receipt and ticket credentials.</li>
              <li>You agree to pay all applicable ticket charges through the payment channels provided on the Platform.</li>
              <li>You agree not to use the Platform for any unlawful, fraudulent, or prohibited purpose under Indian or applicable local laws.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              4. Binding Event Booking Contract &amp; Digital Acknowledgement
            </h2>
            <p>
              Upon completing a ticket payment transaction on the Platform, you enter into a legally binding contract with <strong>MS Naatyakshetra</strong> for admission to the performance of <em>Nritya Bharathanjali 2026 – Skanda</em>.
            </p>
            <p className="mt-2">
              All ticket confirmations and receipts are delivered strictly in digital format (via email confirmation, SMS notification, and/or downloadable web receipt). No physical paper tickets or physical postal shipments will be dispatched.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              5. Refund &amp; Cancellation Terms Summary
            </h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Non-Refundable:</strong> All ticket bookings are strictly non-refundable and non-cancellable by the user once confirmed.</li>
              <li><strong>Organizer Cancellation:</strong> Refunds are granted solely in the event that the performance is officially cancelled by MS Naatyakshetra.</li>
              <li><strong>Duplicate Payments:</strong> In the event of a technical duplicate payment error, verified extra debits will be refunded back to the original payment source.</li>
            </ul>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              6. Venue Entry &amp; Event Rules
            </h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Each digital ticket grants entry for one individual to the designated category for the performance on September 26, 2026.</li>
              <li>Attendees must present their digital e-ticket/acknowledgement receipt alongside a valid government-issued photo ID at the venue entrance.</li>
              <li>MS Naatyakshetra reserves the right of admission. Late entry, disruptive behavior, or venue violation may result in denied entry without refund.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              7. Proprietary Intellectual Property Rights
            </h2>
            <p>
              All contents, choreography details, production graphics, artwork, emblems, layout, audio-visual materials, and software components on this Platform are the exclusive intellectual property of MS Naatyakshetra. You may not copy, reproduce, distribute, or create derivative works without prior written consent.
            </p>
          </section>

          {/* Section 8 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              8. Force Majeure &amp; Limitation of Liability
            </h2>
            <p>
              Neither party shall be held liable for failure or delay in performing obligations under these Terms if performance is prevented or delayed by events beyond control (including natural disasters, government restrictions, severe weather, or venue emergency conditions). MS Naatyakshetra shall not be liable for indirect, incidental, or server outage damages.
            </p>
          </section>

          {/* Section 9 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              9. Governing Law &amp; Jurisdiction
            </h2>
            <p>
              These Terms &amp; Conditions shall be governed by and construed in accordance with the laws of India. All disputes, claims, or legal actions arising out of or in connection with the Platform or event bookings shall be subject to the <strong>exclusive jurisdiction of the competent courts in Bengaluru, Karnataka, India</strong>.
            </p>
          </section>

          {/* Section 10 */}
          <section>
            <h2 className="text-xl font-bold font-serif-display mb-3" style={{ color: 'var(--maroon)' }}>
              10. Entity &amp; Contact Details
            </h2>
            <div className="p-4 rounded-lg border text-xs space-y-1" style={{ background: 'var(--sandal)', borderColor: 'var(--gold)' }}>
              <p><strong>Organizer Name:</strong> MS Naatyakshetra</p>
              <p><strong>Full Address:</strong> 1, Jayaramreddy layout, 2nd Main, 3rd Cross A-Block, AECS Layout, Kundalahalli, Brookefield, Bengaluru, Karnataka 560037</p>
              <p><strong>Contact Email:</strong> NIL</p>
              <p><strong>Support Phone:</strong> NIL</p>
            </div>
          </section>
        </div>

        {/* Footer Navigation Back Links */}
        <div className="mt-8 pt-6 border-t flex flex-wrap justify-between items-center text-xs gap-4" style={{ borderColor: 'var(--gold)' }}>
          <span style={{ color: 'var(--ink-soft)' }}>&copy; 2026 MS Naatyakshetra. All Rights Reserved.</span>
          <div className="flex gap-4">
            <Link href="/privacy-policy" className="hover:underline" style={{ color: 'var(--maroon)' }}>Privacy Policy</Link>
            <Link href="/refund-policy" className="hover:underline" style={{ color: 'var(--maroon)' }}>Refund Policy</Link>
            <Link href="/return-policy" className="hover:underline" style={{ color: 'var(--maroon)' }}>Return Policy</Link>
            <Link href="/shipping-policy" className="hover:underline" style={{ color: 'var(--maroon)' }}>Digital Delivery</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
